// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`     // XRAY, SINGBOX, V2RAY
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // JSON configuration
	Users         []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	KeepAlive     bool                   `protobuf:"varint,4,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Backend) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Backend) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Backend) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Proxies       []*Proxy               `protobuf:"bytes,2,rep,name=proxies,proto3" json:"proxies,omitempty"`
	Inbounds      []string               `protobuf:"bytes,3,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetProxies() []*Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *User) GetInbounds() []string {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmessId       string                 `protobuf:"bytes,1,opt,name=vmess_id,json=vmessId,proto3" json:"vmess_id,omitempty"`
	VlessId       string                 `protobuf:"bytes,2,opt,name=vless_id,json=vlessId,proto3" json:"vless_id,omitempty"`
	VlessFlow     string                 `protobuf:"bytes,3,opt,name=vless_flow,json=vlessFlow,proto3" json:"vless_flow,omitempty"`
	TrojanPwd     string                 `protobuf:"bytes,4,opt,name=trojan_pwd,json=trojanPwd,proto3" json:"trojan_pwd,omitempty"`
	SsMethod      string                 `protobuf:"bytes,5,opt,name=ss_method,json=ssMethod,proto3" json:"ss_method,omitempty"`
	SsPass        string                 `protobuf:"bytes,6,opt,name=ss_pass,json=ssPass,proto3" json:"ss_pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *Proxy) GetVmessId() string {
	if x != nil {
		return x.VmessId
	}
	return ""
}

func (x *Proxy) GetVlessId() string {
	if x != nil {
		return x.VlessId
	}
	return ""
}

func (x *Proxy) GetVlessFlow() string {
	if x != nil {
		return x.VlessFlow
	}
	return ""
}

func (x *Proxy) GetTrojanPwd() string {
	if x != nil {
		return x.TrojanPwd
	}
	return ""
}

func (x *Proxy) GetSsMethod() string {
	if x != nil {
		return x.SsMethod
	}
	return ""
}

func (x *Proxy) GetSsPass() string {
	if x != nil {
		return x.SsPass
	}
	return ""
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type BaseInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CoreType      string                 `protobuf:"bytes,2,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	XrayVersion   string                 `protobuf:"bytes,4,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	Uptime        int64                  `protobuf:"varint,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfoResponse) Reset() {
	*x = BaseInfoResponse{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoResponse) ProtoMessage() {}

func (x *BaseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoResponse.ProtoReflect.Descriptor instead.
func (*BaseInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *BaseInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BaseInfoResponse) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *BaseInfoResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *BaseInfoResponse) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *BaseInfoResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *BaseInfoResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *Log) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SyncedCount   int32                  `protobuf:"varint,3,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // UsersStat, UserStat, Inbounds, etc
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // user email or inbound tag
	Reset_        bool                   `protobuf:"varint,3,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *StatsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StatsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BytesUp       int64                  `protobuf:"varint,2,opt,name=bytes_up,json=bytesUp,proto3" json:"bytes_up,omitempty"`
	BytesDown     int64                  `protobuf:"varint,3,opt,name=bytes_down,json=bytesDown,proto3" json:"bytes_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatsResponse) GetBytesUp() int64 {
	if x != nil {
		return x.BytesUp
	}
	return 0
}

func (x *StatsResponse) GetBytesDown() int64 {
	if x != nil {
		return x.BytesDown
	}
	return 0
}

type SystemStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemTotal      int64                  `protobuf:"varint,3,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed       int64                  `protobuf:"varint,4,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	MemUsage      float64                `protobuf:"fixed64,5,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	NetRx         int64                  `protobuf:"varint,6,opt,name=net_rx,json=netRx,proto3" json:"net_rx,omitempty"`
	NetTx         int64                  `protobuf:"varint,7,opt,name=net_tx,json=netTx,proto3" json:"net_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	mi := &file_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *SystemStatsResponse) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemStatsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemStatsResponse) GetMemTotal() int64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SystemStatsResponse) GetMemUsed() int64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemStatsResponse) GetMemUsage() float64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *SystemStatsResponse) GetNetRx() int64 {
	if x != nil {
		return x.NetRx
	}
	return 0
}

func (x *SystemStatsResponse) GetNetTx() int64 {
	if x != nil {
		return x.NetTx
	}
	return 0
}

type OnlineUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*OnlineUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUsersResponse) Reset() {
	*x = OnlineUsersResponse{}
	mi := &file_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUsersResponse) ProtoMessage() {}

func (x *OnlineUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUsersResponse.ProtoReflect.Descriptor instead.
func (*OnlineUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *OnlineUsersResponse) GetUsers() []*OnlineUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type OnlineUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	OnlineSince   int64                  `protobuf:"varint,3,opt,name=online_since,json=onlineSince,proto3" json:"online_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUser) Reset() {
	*x = OnlineUser{}
	mi := &file_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUser) ProtoMessage() {}

func (x *OnlineUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUser.ProtoReflect.Descriptor instead.
func (*OnlineUser) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *OnlineUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OnlineUser) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *OnlineUser) GetOnlineSince() int64 {
	if x != nil {
		return x.OnlineSince
	}
	return 0
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\x04node\"\a\n" +
	"\x05Empty\"v\n" +
	"\aBackend\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12 \n" +
	"\x05users\x18\x03 \x03(\v2\n" +
	".node.UserR\x05users\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x04 \x01(\bR\tkeepAlive\"_\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12%\n" +
	"\aproxies\x18\x02 \x03(\v2\v.node.ProxyR\aproxies\x12\x1a\n" +
	"\binbounds\x18\x03 \x03(\tR\binbounds\"\xb1\x01\n" +
	"\x05Proxy\x12\x19\n" +
	"\bvmess_id\x18\x01 \x01(\tR\avmessId\x12\x19\n" +
	"\bvless_id\x18\x02 \x01(\tR\avlessId\x12\x1d\n" +
	"\n" +
	"vless_flow\x18\x03 \x01(\tR\tvlessFlow\x12\x1d\n" +
	"\n" +
	"trojan_pwd\x18\x04 \x01(\tR\ttrojanPwd\x12\x1b\n" +
	"\tss_method\x18\x05 \x01(\tR\bssMethod\x12\x17\n" +
	"\ass_pass\x18\x06 \x01(\tR\x06ssPass\")\n" +
	"\x05Users\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".node.UserR\x05users\"\xbd\x01\n" +
	"\x10BaseInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\tcore_type\x18\x02 \x01(\tR\bcoreType\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12!\n" +
	"\fxray_version\x18\x04 \x01(\tR\vxrayVersion\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\x03R\x06uptime\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"S\n" +
	"\x03Log\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"e\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fsynced_count\x18\x03 \x01(\x05R\vsyncedCount\"L\n" +
	"\fStatsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05reset\x18\x03 \x01(\bR\x05reset\"]\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bbytes_up\x18\x02 \x01(\x03R\abytesUp\x12\x1d\n" +
	"\n" +
	"bytes_down\x18\x03 \x01(\x03R\tbytesDown\"\xd2\x01\n" +
	"\x13SystemStatsResponse\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tmem_total\x18\x03 \x01(\x03R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x04 \x01(\x03R\amemUsed\x12\x1b\n" +
	"\tmem_usage\x18\x05 \x01(\x01R\bmemUsage\x12\x15\n" +
	"\x06net_rx\x18\x06 \x01(\x03R\x05netRx\x12\x15\n" +
	"\x06net_tx\x18\a \x01(\x03R\x05netTx\"=\n" +
	"\x13OnlineUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.node.OnlineUserR\x05users\"W\n" +
	"\n" +
	"OnlineUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\x12!\n" +
	"\fonline_since\x18\x03 \x01(\x03R\vonlineSince2\xc6\x03\n" +
	"\vNodeService\x12.\n" +
	"\x05Start\x12\r.node.Backend\x1a\x16.node.BaseInfoResponse\x12+\n" +
	"\x04Stop\x12\v.node.Empty\x1a\x16.node.BaseInfoResponse\x122\n" +
	"\vGetBaseInfo\x12\v.node.Empty\x1a\x16.node.BaseInfoResponse\x12#\n" +
	"\aGetLogs\x12\v.node.Empty\x1a\t.node.Log0\x01\x12*\n" +
	"\bSyncUser\x12\n" +
	".node.User\x1a\x12.node.SyncResponse\x12,\n" +
	"\tSyncUsers\x12\v.node.Users\x1a\x12.node.SyncResponse\x123\n" +
	"\bGetStats\x12\x12.node.StatsRequest\x1a\x13.node.StatsResponse\x128\n" +
	"\x0eGetSystemStats\x12\v.node.Empty\x1a\x19.node.SystemStatsResponse\x128\n" +
	"\x0eGetOnlineUsers\x12\v.node.Empty\x1a\x19.node.OnlineUsersResponseB\x17Z\x15xray-panel-node/protob\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_node_proto_goTypes = []any{
	(*Empty)(nil),               // 0: node.Empty
	(*Backend)(nil),             // 1: node.Backend
	(*User)(nil),                // 2: node.User
	(*Proxy)(nil),               // 3: node.Proxy
	(*Users)(nil),               // 4: node.Users
	(*BaseInfoResponse)(nil),    // 5: node.BaseInfoResponse
	(*Log)(nil),                 // 6: node.Log
	(*SyncResponse)(nil),        // 7: node.SyncResponse
	(*StatsRequest)(nil),        // 8: node.StatsRequest
	(*StatsResponse)(nil),       // 9: node.StatsResponse
	(*SystemStatsResponse)(nil), // 10: node.SystemStatsResponse
	(*OnlineUsersResponse)(nil), // 11: node.OnlineUsersResponse
	(*OnlineUser)(nil),          // 12: node.OnlineUser
}
var file_proto_node_proto_depIdxs = []int32{
	2,  // 0: node.Backend.users:type_name -> node.User
	3,  // 1: node.User.proxies:type_name -> node.Proxy
	2,  // 2: node.Users.users:type_name -> node.User
	12, // 3: node.OnlineUsersResponse.users:type_name -> node.OnlineUser
	1,  // 4: node.NodeService.Start:input_type -> node.Backend
	0,  // 5: node.NodeService.Stop:input_type -> node.Empty
	0,  // 6: node.NodeService.GetBaseInfo:input_type -> node.Empty
	0,  // 7: node.NodeService.GetLogs:input_type -> node.Empty
	2,  // 8: node.NodeService.SyncUser:input_type -> node.User
	4,  // 9: node.NodeService.SyncUsers:input_type -> node.Users
	8,  // 10: node.NodeService.GetStats:input_type -> node.StatsRequest
	0,  // 11: node.NodeService.GetSystemStats:input_type -> node.Empty
	0,  // 12: node.NodeService.GetOnlineUsers:input_type -> node.Empty
	5,  // 13: node.NodeService.Start:output_type -> node.BaseInfoResponse
	5,  // 14: node.NodeService.Stop:output_type -> node.BaseInfoResponse
	5,  // 15: node.NodeService.GetBaseInfo:output_type -> node.BaseInfoResponse
	6,  // 16: node.NodeService.GetLogs:output_type -> node.Log
	7,  // 17: node.NodeService.SyncUser:output_type -> node.SyncResponse
	7,  // 18: node.NodeService.SyncUsers:output_type -> node.SyncResponse
	9,  // 19: node.NodeService.GetStats:output_type -> node.StatsResponse
	10, // 20: node.NodeService.GetSystemStats:output_type -> node.SystemStatsResponse
	11, // 21: node.NodeService.GetOnlineUsers:output_type -> node.OnlineUsersResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
