"""Add block_torrents to inbound and max_connections to user

Revision ID: 493d3e718f32
Revises: 692281e7034b
Create Date: 2025-10-05 22:33:11.290851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '493d3e718f32'
down_revision: Union[str, None] = '692281e7034b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('block_torrents', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('max_connections', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_connections')
    op.drop_column('inbounds', 'block_torrents')
    # ### end Alembic commands ###
